echo "$(tput setaf 1)==============================================================================================$(tput sgr 0)"
echo "$(tput setaf 1)||$(tput sgr 0)$(tput setaf 4)   TTTTT  EEEEE     A     MM        MM  MM        MM     A    TTTTT RRRRR   IIIII X    X$(tput sgr 0) $(tput setaf 1) ||$(tput sgr 0)"
echo "$(tput setaf 1)||$(tput sgr 0)$(tput setaf 4)     T    E        A A    M M      M M  M M      M M    A A     T   R   R     I    X X$(tput sgr 0)   $(tput setaf 1) ||$(tput sgr 0)"
echo "$(tput setaf 1)||$(tput sgr 0)$(tput setaf 4)     T    EEEEE   A A A   M  M    M  M  M  M    M  M   A A A    T   R R R     I     X$(tput sgr 0)    $(tput setaf 1) ||$(tput sgr 0)"
echo "$(tput setaf 1)||$(tput sgr 0)$(tput setaf 4)     T    E      A     A  M   M  M   M  M   M  M   M  A     A   T   R    R    I    X  X$(tput sgr 0)  $(tput setaf 1) ||$(tput sgr 0)"
echo "$(tput setaf 1)||$(tput sgr 0)$(tput setaf 4)     T    EEEEE A       A M    MM    M__M    MM    M A       A  T   R     R IIIII X    X$(tput sgr 0) $(tput setaf 1) ||$(tput sgr 0)"
echo "$(tput setaf 1)==============================================================================================$(tput sgr 0)"
echo "               $(tput setaf 6)|$(tput sgr 0)  Developed By      :   N1GHTMAR3                          $(tput setaf 6)|$(tput sgr 0)"
echo "               $(tput setaf 6)|$(tput sgr 0)  Github            :   https://github.com/n1ghtmar3-2421  $(tput setaf 6)|$(tput sgr 0)"
echo "               $(tput setaf 6)|$(tput sgr 0)  Telegram ID       :   https://t.me/n1ghtmar3_2421        $(tput setaf 6)|$(tput sgr 0)"
echo "               $(tput setaf 6)|$(tput sgr 0)  Telegram Channel  :   https://t.me/teammatrixx           $(tput setaf 6)|$(tput sgr 0)"
echo "               $(tput setaf 6)|===========================================================|$(tput sgr 0)"
